"""added users.is_moderator

Revision ID: 2a96b6b05aec
Revises: a0668b6a54e6
Create Date: 2021-01-25 02:43:45.789264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a96b6b05aec'
down_revision = 'a0668b6a54e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_group_moderator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_group_moderator')
    # ### end Alembic commands ###
