"""added User.subgroups

Revision ID: 59695dbfeafe
Revises: 2606ce1554df
Create Date: 2021-01-27 13:57:43.004637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59695dbfeafe'
down_revision = '2606ce1554df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
