"""added SingleLesson.comment

Revision ID: b27b7aeb8ee6
Revises: 943f6b886942
Create Date: 2021-02-05 19:28:56.710040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27b7aeb8ee6'
down_revision = '943f6b886942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('single_lessons', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('single_lessons', 'comment')
    # ### end Alembic commands ###
