version: "3.7"

services:
  bot:
    image: "${DOCKER_IMAGE:-knu_assistant}:${DOCKER_TAG_BASE-latest}"
    build:
      context: "assistant"
      dockerfile: "Dockerfile"
      args:
        DEBUG: ${DEBUG:-false}
    environment:
      - DEBUG=${DEBUG:-false}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - TELEGRAM_BOT_WORKERS=${TELEGRAM_BOT_WORKERS:-1}
    command: "bash scripts/run-bot.sh"

  celery:
    image: "${DOCKER_IMAGE_BASE:-knu_assistant}:${DOCKER_TAG_BASE-latest}"
    build:
      context: "assistant"
      dockerfile: "Dockerfile"
      args:
        DEBUG: ${DEBUG:-false}
    environment:
      - DEBUG=${DEBUG:-false}
      - SENTRY_DSN=${SENTRY_DSN:-}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DB=${REDIS_DB:-0}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
      - CELERY_WORKERS=${CELERY_WORKERS:-1}
    command: "bash scripts/run-celery.sh"
